[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"
extend-exclude = ["prompts.py", "views.py", "*/migrations/*.py"] # Views is temporarily not linted until we can coordinate a time to fix it

[tool.ruff.lint]
select = [
    "ALL", # include all the rules, including new ones
]
ignore = ["PLR0913", "D413", "TRY201", "RET504", "PLR5501", "D202", "D213", "EM101", "TRY003", "G004", "COM812", "FBT002", "FBT001", "FBT003", "C901", "PT009", "PT027", "ANN101", "ISC001", "RUF100", "DJ001"]
extend-select = []

[tool.ruff.lint.pydocstyle]
convention = "google"