# Generated by Django 4.2.8 on 2025-06-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=255)),
                ("journal", models.CharField(max_length=255)),
                ("invivo_model", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("condition_sets", models.JSONField(default=list)),
                ("is_important", models.BooleanField(default=False)),
            ],
        ),
    ]
